//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reticule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserver
    {
        public int IdReservation { get; set; }
        public Nullable<System.DateTime> Date2Debut { get; set; }
        public Nullable<System.DateTime> Date2Fin { get; set; }
        public Nullable<int> SalleID { get; set; }
        public Nullable<int> EMID { get; set; }
    
        public virtual Equipement_Mobile Equipement_Mobile { get; set; }
        public virtual Salle Salle { get; set; }
    }
}
