//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reticule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Salle()
        {
            this.Reservers = new HashSet<Reserver>();
        }
    
        public int SalleID { get; set; }
        public string NomSalle { get; set; }
        public string Batiment { get; set; }
        public string Etage { get; set; }
        public Nullable<int> EMID { get; set; }
        public Nullable<int> EFID { get; set; }
    
        public virtual Equipement_Fixe Equipement_Fixe { get; set; }
        public virtual Equipement_Mobile Equipement_Mobile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserver> Reservers { get; set; }
    }
}
